rpc:
  registerIP: ""
  listenIP: 0.0.0.0
  autoSetPorts: true
  ports: []
ratelimiter:
  enable: false
  window: 20s
  bucket: 500
  cpuThreshold: 850
circuitBreaker:
  enable: false
  window: 5s
  bucket: 100
  success: 0.6
  request: 500
prometheus:
  enable: false
  ports: []
maxConcurrentWorkers: 3
enable: {}
getui:
  pushUrl: https://restapi.getui.com/v2/$appId
  masterSecret: ""
  appKey: ""
  intent: ""
  channelID: ""
  channelName: ""
fcm:
  filePath: ""
  authURL: ""
jpush:
  appKey: ""
  pushURL: ""
  pushIntent: ""
iosPush:
  pushSound: xxx
  badgeCount: true
  production: false
fullUserCache: true
