apisix:
  node_listen: 9080
  admin_key:
    - name: admin
      key: edd1c9f034335f136f87ad84b625c8f1   # 使用随机字符串
      role: admin
deployment:
  role: traditional
  etcd:
    host:
      - http://etcd:2379
  admin:
    enable_admin_ui: true        # 启用内嵌 Dashboard
    admin_key:
      - name: admin
        key: edd1c9f034335f136f87ad84b625c8f1   # 与上面保持一致
        role: admin